name: Create Github Issues in JIRA

# this action is triggered when a Github issue is created
on:
  issues:
    types: [opened, edited]

jobs:
  create-jira-issue-from-github-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Log secret
        run: echo "base url ${{ secrets.JIRA_BASE_URL }}"

      - name: Login to JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_JONS_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_JONS_ACCOUNT }}
